#!/usr/bin/ruby
cody_version = '0.0.2'

if ARGV.length == 0
    puts "Cody start v#{cody_version}" 
    `bundle exec guard`
else
    if ARGV[0].match /^[setup|s]$/
        `bundle install`
         #todo : make cody config
         puts "not ready to make config"
    end
    if ARGV[0].match /^[deploy|d]$/
        puts "not ready to make deploy"
    end
end